CREATE DATABASE cardenas_db;
USE cardenas_db;

CREATE TABLE Aula (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    numero VARCHAR(10) NOT NULL,
    planta ENUM('1', '2', '3', '4', '5') NOT NULL DEFAULT '1',
    situacion ENUM('DISPONIBLE', 'OCUPADA', 'EN MANTENIMIENTO') NOT NULL DEFAULT 'DISPONIBLE'
);

CREATE TABLE Estudiante (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    numero_matricula VARCHAR(50) UNIQUE NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    direccion TEXT NOT NULL
);

CREATE TABLE Asignatura (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    ciclo ENUM('I', 'II', 'III') NOT NULL DEFAULT 'I',
    descripcion TEXT NOT NULL
);

CREATE TABLE Estudia (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    estudiante_id BIGINT UNSIGNED NOT NULL,
    asignatura_id BIGINT UNSIGNED NOT NULL,
    aula_id BIGINT UNSIGNED NOT NULL,
    hora TIME NOT NULL DEFAULT '08:00:00',
    FOREIGN KEY (estudiante_id) REFERENCES Estudiante(id) ON DELETE CASCADE,
    FOREIGN KEY (asignatura_id) REFERENCES Asignatura(id) ON DELETE CASCADE,
    FOREIGN KEY (aula_id) REFERENCES Aula(id) ON DELETE CASCADE
);
